import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  id: {
    // Landing Page
    'landing.heroTitle': 'Sistem Absensi Modern',
    'landing.heroSubtitle': 'Pelacakan absensi berbasis GPS dengan validasi real-time, manajemen shift, dan pelaporan komprehensif',
    'landing.getStarted': 'Mulai Sekarang',
    'landing.signIn': 'Masuk',
    'landing.powerfulFeatures': 'Fitur Unggulan',
    'landing.featuresSubtitle': 'Semua yang Anda butuhkan untuk manajemen absensi modern',
    'landing.gpsValidation': 'Validasi GPS',
    'landing.gpsValidationDesc': 'Verifikasi lokasi otomatis memastikan karyawan berada di lokasi kerja yang ditentukan',
    'landing.smartTimeTracking': 'Pelacakan Waktu Cerdas',
    'landing.smartTimeTrackingDesc': 'Pemantauan absensi real-time dengan validasi berbasis shift dan deteksi keterlambatan',
    'landing.mobileFirstDesign': 'Desain Mobile-First',
    'landing.mobileFirstDesignDesc': 'Dioptimalkan untuk perangkat mobile dengan desain responsif dan geolokasi native',
    'landing.makeupRequests': 'Permintaan Make-up',
    'landing.makeupRequestsDesc': 'Sistem mudah untuk karyawan mengajukan permintaan waktu make-up untuk absensi yang terlewat',
    'landing.roleBasedAccess': 'Akses Berbasis Peran',
    'landing.roleBasedAccessDesc': 'Interface dan izin terpisah untuk karyawan dan administrator',
    'landing.advancedReporting': 'Pelaporan Lanjutan',
    'landing.advancedReportingDesc': 'Analitik komprehensif dengan kemampuan ekspor untuk laporan CSV dan PDF',
    'landing.antiFraudSystem': 'Sistem Anti-Fraud',
    'landing.antiFraudSystemDesc': 'Deteksi lokasi palsu, validasi perangkat, dan pemeriksaan kecepatan untuk mencegah manipulasi absensi',
    'landing.howItWorks': 'Cara Kerja',
    'landing.howItWorksSubtitle': 'Langkah sederhana untuk pelacakan absensi modern',
    'landing.step1Title': 'Check In',
    'landing.step1Desc': 'Karyawan membuka aplikasi dan tap check-in. GPS secara otomatis memvalidasi lokasi mereka.',
    'landing.step2Title': 'Validasi Real-time',
    'landing.step2Desc': 'Sistem memvalidasi lokasi, waktu, dan jadwal shift untuk menentukan status absensi.',
    'landing.step3Title': 'Analitik & Laporan',
    'landing.step3Desc': 'Admin dapat melihat data real-time, membuat laporan, dan mengelola permintaan make-up.',
    'landing.readyToModernize': 'Siap Modernisasi Sistem Absensi Anda?',
    'landing.readyToModernizeDesc': 'Bergabunglah dengan organisasi yang mempercayai sistem absensi berbasis GPS kami untuk pelacakan yang akurat dan real-time.',
    'landing.startFreeToday': 'Mulai Gratis Hari Ini',
    'landing.footerText': '© 2025 All rights reserved. Gracefully made by Allah for Symbiotech.',
    
    // Auth
    'auth.signIn': 'Masuk',
    'auth.signUp': 'Daftar',
    'auth.email': 'Email',
    'auth.password': 'Kata Sandi',
    'auth.name': 'Nama',
    'auth.confirmPassword': 'Konfirmasi Kata Sandi',
    'auth.forgotPassword': 'Lupa Kata Sandi?',
    'auth.alreadyHaveAccount': 'Sudah punya akun?',
    'auth.dontHaveAccount': 'Belum punya akun?',
    'auth.signOut': 'Keluar',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Selamat datang kembali',
    'dashboard.checkInToday': 'Absen Hari Ini',
    'dashboard.currentTime': 'Waktu saat ini',
    'dashboard.alreadyCheckedIn': 'Sudah Absen',
    'dashboard.time': 'Waktu',
    'dashboard.checkInNow': 'Absen Sekarang',
    'dashboard.clockOut': 'Clock Out',
    'dashboard.clockOutNow': 'Clock Out Sekarang',
    'dashboard.checkingLocation': 'Memeriksa lokasi...',
    'dashboard.makeValidLocation': 'Pastikan Anda berada di lokasi yang valid',
    'dashboard.validLocations': 'Lokasi Valid',
    'dashboard.radius': 'Radius',
    'dashboard.missedAttendance': 'Terlewat Absen?',
    'dashboard.requestMakeup': 'Ajukan permintaan makeup untuk absen yang terlewat',
    'dashboard.thisMonth': 'Bulan Ini',
    'dashboard.totalDays': 'Total Hari',
    'dashboard.present': 'Hadir',
    'dashboard.late': 'Terlambat',
    'dashboard.absent': 'Tidak Hadir',
    
    // Camera & Photo
    'camera.takingPhoto': 'Mengambil foto...',
    'camera.photoTaken': 'Foto berhasil diambil',
    'camera.photoFailed': 'Gagal mengambil foto',
    'camera.cameraNotAvailable': 'Kamera tidak tersedia',
    'camera.permissionDenied': 'Izin kamera ditolak',
    'camera.usingFallback': 'Menggunakan foto cadangan',
    'camera.photoSaved': 'Foto tersimpan dengan aman',
    'camera.attendanceWithPhoto': 'Absensi dengan foto berhasil',
    'camera.attendanceWithoutPhoto': 'Absensi tanpa foto berhasil',
    'camera.securePhotoCapture': 'Pengambilan foto aman',
    
    // Shift Selection
    'shift.todayShiftSelection': 'Pilihan Shift Hari Ini',
    'shift.chooseWorkingShift': 'Pilih shift kerja Anda untuk',
    'shift.selectShift': 'Pilih Shift',
    'shift.chooseShiftToday': 'Pilih shift Anda untuk hari ini',
    'shift.currentShift': 'Shift Saat Ini',
    'shift.startTime': 'Waktu Mulai',
    'shift.endTime': 'Waktu Selesai',
    'shift.duration': 'Durasi',
    'shift.dayType': 'Jenis Hari',
    'shift.todayTimeline': 'Timeline Hari Ini',
    'shift.start': 'Mulai',
    'shift.end': 'Selesai',
    'shift.availableShifts': 'Shift Tersedia untuk',
    'shift.refreshShifts': 'Perbarui Shift',
    'shift.cannotChangeAfterAttendance': 'Shift tidak dapat diubah setelah absen tercatat untuk hari ini.',
    'shift.shiftChangedSuccess': 'Shift berhasil diubah ke',
    'shift.selectShiftFirst': 'Pilih Shift Terlebih Dahulu',
    'shift.chooseShiftBeforeCheckin': 'Silakan pilih shift kerja Anda di atas sebelum melakukan absen.',
    'shift.selectedShift': 'Shift Terpilih',
    'shift.shiftRequired': 'Shift Diperlukan',
    'shift.pleaseSelectShift': 'Silakan pilih shift Anda sebelum melakukan check-in.',
    'shift.shiftStarts': 'Shift dimulai pada',
    'shift.shiftActive': 'Shift aktif hingga',
    'shift.shiftEnded': 'Shift berakhir pada',
    
    // Shift Status
    'shift.status.active': 'Aktif Sekarang',
    'shift.status.upcoming': 'Akan Datang',
    'shift.status.ended': 'Berakhir',
    'shift.status.before': 'Sebelum Shift',
    'shift.status.during': 'Selama Shift',
    'shift.status.after': 'Setelah Shift',
    
    // Day Types
    'dayType.weekday': 'Hari Kerja',
    'dayType.weekend': 'Akhir Pekan',
    'dayType.holiday': 'Hari Libur',
    'dayType.all': 'Semua Hari',
    
    // Admin Dashboard
    'admin.dashboard': 'Dashboard Admin',
    'admin.welcomeBack': 'Selamat datang kembali',
    'admin.reports': 'Laporan',
    'admin.users': 'Pengguna',
    'admin.devices': 'Perangkat',
    'admin.locations': 'Lokasi',
    'admin.shifts': 'Shift',
    'admin.makeupRequests': 'Permintaan Make-up',
    
    // Analytics
    'analytics.todayOverview': 'Ringkasan Hari Ini',
    'analytics.presentToday': 'Hadir Hari Ini',
    'analytics.lateToday': 'Terlambat Hari Ini',
    'analytics.absentToday': 'Tidak Hadir Hari Ini',
    'analytics.totalEmployees': 'Total Karyawan',
    'analytics.activeUsers': 'Pengguna Aktif',
    'analytics.ofTotal': 'dari total',
    'analytics.performanceMetrics': 'Metrik Kinerja',
    'analytics.attendanceRate': 'Tingkat Kehadiran',
    'analytics.punctualityRate': 'Tingkat Ketepatan Waktu',
    'analytics.thisMonth': 'Bulan Ini',
    'analytics.fromLastMonth': 'dari bulan lalu',
    'analytics.securityLocationAnalytics': 'Analitik Keamanan & Lokasi',
    'analytics.securityRiskDistribution': 'Distribusi Risiko Keamanan',
    'analytics.lowRisk': 'Risiko Rendah',
    'analytics.mediumRisk': 'Risiko Sedang',
    'analytics.highRisk': 'Risiko Tinggi',
    'analytics.popularLocations': 'Lokasi Populer',
    'analytics.checkIns': 'check-in',
    'analytics.analyticsDashboard': 'Dashboard Analitik',
    'analytics.detailedReports': 'Laporan Detail',
    'analytics.noLocationData': 'Belum ada data lokasi',
    
    // Device Management
    'device.deviceManagement': 'Manajemen Perangkat',
    'device.manageDevices': 'Kelola perangkat pengguna, reset sidik jari, dan pantau keamanan',
    'device.filterByUser': 'Filter berdasarkan Pengguna',
    'device.allUsers': 'Semua Pengguna',
    'device.refresh': 'Perbarui',
    'device.registeredDevices': 'Perangkat Terdaftar',
    'device.uniqueDevicesFound': 'perangkat unik ditemukan',
    'device.user': 'Pengguna',
    'device.deviceInfo': 'Info Perangkat',
    'device.riskLevel': 'Level Risiko',
    'device.lastSeen': 'Terakhir Dilihat',
    'device.securityStatus': 'Status Keamanan',
    'device.warnings': 'peringatan',
    'device.clean': 'Bersih',
    'device.deviceDetails': 'Detail Perangkat',
    'device.detailedInformation': 'Informasi detail tentang perangkat ini dan status keamanannya',
    'device.deviceFingerprint': 'Sidik Jari Perangkat',
    'device.deviceInformation': 'Informasi Perangkat',
    'device.securityWarnings': 'Peringatan Keamanan',
    'device.lastActivity': 'Aktivitas Terakhir',
    'device.resetDevice': 'Reset Perangkat',
    'device.resetDeviceFingerprint': 'Reset Sidik Jari Perangkat',
    'device.resetConfirmation': 'Tindakan ini akan mereset sidik jari perangkat untuk pengguna ini. Mereka perlu mendaftarkan ulang perangkat mereka pada login berikutnya.',
    'device.confirmReset': 'Konfirmasi Reset',
    'device.currentRisk': 'Risiko Saat Ini',
    'device.processing': 'Memproses...',
    'device.deviceResetSuccess': 'Sidik jari perangkat berhasil direset untuk pengguna',
    'device.unknownDevice': 'Perangkat Tidak Dikenal',
    
    // Security
    'security.securityStatus': 'Status Keamanan',
    'security.mockLocationDetection': 'Deteksi Lokasi Palsu',
    'security.deviceFingerprinting': 'Sidik Jari Perangkat',
    'security.velocityCheck': 'Pemeriksaan Kecepatan',
    'security.active': 'Aktif',
    'security.securityAlert': 'Peringatan Keamanan - Level Risiko',
    'security.securityWarning': 'Peringatan Keamanan',
    'security.locationValidationFailed': 'Validasi lokasi gagal. Level risiko',
    'security.confidence': 'Kepercayaan',
    'security.proceedQuestion': 'Apakah Anda ingin melanjutkan?',
    'security.protectedByAntiFraud': 'Dilindungi oleh sistem anti-fraud',
    
    // Device Management
    'admin.deviceManagement': 'Manajemen Perangkat',
    'admin.manageDevices': 'Kelola perangkat pengguna dan keamanan',
    'admin.deviceInfo': 'Info Perangkat',
    'admin.lastSeen': 'Terakhir Dilihat',
    'admin.securityStatus': 'Status Keamanan',
    'admin.resetDevice': 'Reset Perangkat',
    'admin.deviceReset': 'Perangkat berhasil direset!',
    'admin.resetConfirm': 'Apakah Anda yakin ingin mereset perangkat ini?',
    'admin.deviceDetails': 'Detail Perangkat',
    'admin.securityWarnings': 'Peringatan Keamanan',
    'admin.deviceFingerprint': 'Sidik Jari Perangkat',
    'admin.riskLevel': 'Level Risiko',
    'admin.clean': 'Bersih',
    'admin.warnings': 'peringatan',
    
    // Admin Reports
    'admin.filterExport': 'Filter & Ekspor',
    'admin.filterAttendanceData': 'Filter data absensi dan ekspor laporan',
    'admin.startDate': 'Tanggal Mulai',
    'admin.endDate': 'Tanggal Akhir',
    'admin.employee': 'Karyawan',
    'admin.allEmployees': 'Semua Karyawan',
    'admin.allStatuses': 'Semua Status',
    'admin.allMethods': 'Semua Metode',
    'admin.regular': 'Reguler',
    'admin.makeup': 'Make-up',
    'admin.reset': 'Reset',
    'admin.csv': 'CSV',
    'admin.attendanceReport': 'Laporan Absensi',
    'admin.recordsFound': 'catatan ditemukan',
    'admin.date': 'Tanggal',
    'admin.exportSuccess': 'Laporan berhasil diekspor!',
    
    // Hours Report - NEW TRANSLATIONS
    'admin.hoursReport': 'Laporan Jam Kerja',
    'admin.hoursReportDescription': 'Analisis jam kerja karyawan berdasarkan shift dan waktu aktual',
    'admin.expectedHours': 'Jam Diharapkan',
    'admin.actualHours': 'Jam Aktual',
    'admin.missingHours': 'Kekurangan Jam',
    'admin.overtimeHours': 'Kelebihan Jam',
    'admin.workingDays': 'Hari Kerja',
    'admin.totalExpectedHours': 'Total Jam Diharapkan',
    'admin.totalActualHours': 'Total Jam Aktual',
    'admin.totalMissingHours': 'Total Kekurangan Jam',
    'admin.totalOvertimeHours': 'Total Kelebihan Jam',
    'admin.averageHoursPerDay': 'Rata-rata Jam per Hari',
    'admin.hoursEfficiency': 'Efisiensi Jam Kerja',
    'admin.noClockOut': 'Belum Clock Out',
    'admin.incomplete': 'Tidak Lengkap',
    'admin.hoursAnalysis': 'Analisis Jam Kerja',
    'admin.employeeHoursSummary': 'Ringkasan Jam Kerja Karyawan',
    
    // Admin User Management
    'admin.userManagement': 'Manajemen Pengguna',
    'admin.manageUsers': 'Kelola akun pengguna dan peran',
    'admin.admin': 'Admin',
    'admin.user': 'Pengguna',
    
    // Admin Location Management
    'admin.locationManagement': 'Manajemen Lokasi',
    'admin.manageValidLocations': 'Kelola lokasi absensi yang valid dengan koordinat GPS',
    'admin.addLocation': 'Tambah Lokasi',
    'admin.editLocation': 'Edit Lokasi',
    'admin.addNewLocation': 'Tambah Lokasi Baru',
    'admin.setupValidLocation': 'Atur lokasi absensi yang valid dengan koordinat GPS dan radius.',
    'admin.locationName': 'Nama Lokasi',
    'admin.locationNamePlaceholder': 'mis., Kantor Pusat',
    'admin.latitude': 'Latitude',
    'admin.longitude': 'Longitude',
    'admin.radiusMeters': 'Radius (meter)',
    'admin.active': 'Aktif',
    'admin.coordinates': 'Koordinat',
    'admin.status': 'Status',
    'admin.inactive': 'Tidak Aktif',
    'admin.deleteLocationConfirm': 'Apakah Anda yakin ingin menghapus lokasi ini?',
    'admin.locationCreated': 'Lokasi berhasil dibuat!',
    'admin.locationUpdated': 'Lokasi berhasil diperbarui!',
    'admin.locationDeleted': 'Lokasi berhasil dihapus!',
    
    // Admin Shift Management
    'admin.shiftManagement': 'Manajemen Shift',
    'admin.manageWorkShifts': 'Kelola shift kerja dan jadwal waktu',
    'admin.addShift': 'Tambah Shift',
    'admin.editShift': 'Edit Shift',
    'admin.addNewShift': 'Tambah Shift Baru',
    'admin.setupWorkShift': 'Atur waktu shift kerja untuk pelacakan absensi.',
    'admin.shiftName': 'Nama Shift',
    'admin.shiftNamePlaceholder': 'mis., Shift Pagi',
    'admin.startTime': 'Waktu Mulai',
    'admin.endTime': 'Waktu Selesai',
    'admin.duration': 'Durasi',
    'admin.hours': 'jam',
    'admin.dayType': 'Jenis Hari',
    'admin.selectDayType': 'Pilih Jenis Hari',
    'admin.dayType.weekday': 'Hari Kerja',
    'admin.dayType.weekend': 'Akhir Pekan',
    'admin.dayType.holiday': 'Hari Libur',
    'admin.dayType.all': 'Semua Hari',
    'admin.deleteShiftConfirm': 'Apakah Anda yakin ingin menghapus shift ini?',
    'admin.shiftCreated': 'Shift berhasil dibuat!',
    'admin.shiftUpdated': 'Shift berhasil diperbarui!',
    'admin.shiftDeleted': 'Shift berhasil dihapus!',
    
    // Admin Makeup Requests
    'admin.makeupRequestsTitle': 'Permintaan Make-up',
    'admin.reviewProcessRequests': 'Tinjau dan proses permintaan absensi make-up karyawan',
    'admin.reason': 'Alasan',
    'admin.submitted': 'Diajukan',
    'admin.reviewMakeupRequest': 'Tinjau Permintaan Make-up',
    'admin.reviewDetails': 'Tinjau detail dan setujui atau tolak permintaan make-up ini.',
    'admin.dateOfMissed': 'Tanggal Absen yang Terlewat',
    'admin.supportingDocument': 'Dokumen Pendukung',
    'admin.viewDocument': 'Lihat Dokumen',
    'admin.adminNotes': 'Catatan Admin',
    'admin.addNotesDecision': 'Tambahkan catatan tentang keputusan Anda...',
    'admin.reject': 'Tolak',
    'admin.approve': 'Setujui',
    'admin.makeupRequestApproved': 'Permintaan make-up disetujui dan catatan absensi dibuat!',
    'admin.makeupRequestRejected': 'Permintaan make-up ditolak.',
    
    // Makeup Request Dialog
    'makeup.requestMakeup': 'Ajukan Make-up',
    'makeup.requestMakeupTime': 'Ajukan Waktu Make-up',
    'makeup.requestMakeupDescription': 'Ajukan permintaan untuk absensi yang terlewat. Admin akan meninjau dan menyetujui.',
    'makeup.dateOfMissedAttendance': 'Tanggal Absen yang Terlewat',
    'makeup.reasonPlaceholder': 'Jelaskan mengapa Anda melewatkan absensi...',
    'makeup.supportingDocumentOptional': 'URL Dokumen Pendukung (Opsional)',
    'makeup.documentUrlPlaceholder': 'https://contoh.com/dokumen.pdf',
    'makeup.submitting': 'Mengirim...',
    'makeup.submitRequest': 'Kirim Permintaan',
    'makeup.requestSubmittedSuccess': 'Permintaan make-up berhasil diajukan!',
    
    // Status
    'status.HADIR': 'HADIR',
    'status.TERLAMBAT': 'TERLAMBAT',
    'status.MAKE_UP': 'MAKE UP',
    'status.pending': 'MENUNGGU',
    'status.approved': 'DISETUJUI',
    'status.rejected': 'DITOLAK',
    
    // General
    'general.success': 'Berhasil',
    'general.error': 'Error',
    'general.loading': 'Memuat...',
    'general.save': 'Simpan',
    'general.cancel': 'Batal',
    'general.delete': 'Hapus',
    'general.edit': 'Edit',
    'general.add': 'Tambah',
    'general.view': 'Lihat',
    'general.actions': 'Aksi',
    'general.name': 'Nama',
    'general.created': 'Dibuat',
    'general.role': 'Peran',
    'general.create': 'Buat',
    'general.update': 'Perbarui',
    'general.time': 'Waktu',
    'general.location': 'Lokasi',
    'general.method': 'Metode',
    'general.close': 'Tutup',
    
    // Attendance
    'attendance.history': 'Riwayat Absensi',
    'attendance.status': 'Status',
    'attendance.method': 'Metode',
    'attendance.location': 'Lokasi',
    'attendance.reason': 'Alasan',
    'attendance.noRecords': 'Tidak ada data absensi',
    
    // Notifications
    'notification.locationError': 'Error Lokasi',
    'notification.notValidLocation': 'Anda tidak berada di lokasi yang valid untuk absen',
    'notification.attendanceSuccess': 'Absen berhasil! Status',
    'notification.roleUpdated': 'Peran pengguna berhasil diperbarui!',
    
    // Language
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English'
  },
  en: {
    // Landing Page
    'landing.heroTitle': 'Modern Attendance System',
    'landing.heroSubtitle': 'GPS-powered attendance tracking with real-time validation, shift management, and comprehensive reporting',
    'landing.getStarted': 'Get Started',
    'landing.signIn': 'Sign In',
    'landing.powerfulFeatures': 'Powerful Features',
    'landing.featuresSubtitle': 'Everything you need for modern attendance management',
    'landing.gpsValidation': 'GPS Validation',
    'landing.gpsValidationDesc': 'Automatic location verification ensures employees are at designated work locations',
    'landing.smartTimeTracking': 'Smart Time Tracking',
    'landing.smartTimeTrackingDesc': 'Real-time attendance monitoring with shift-based validation and late detection',
    'landing.mobileFirstDesign': 'Mobile-First Design',
    'landing.mobileFirstDesignDesc': 'Optimized for mobile devices with responsive design and native geolocation',
    'landing.makeupRequests': 'Make-up Requests',
    'landing.makeupRequestsDesc': 'Easy system for employees to request make-up time for missed attendance',
    'landing.roleBasedAccess': 'Role-Based Access',
    'landing.roleBasedAccessDesc': 'Separate interfaces and permissions for employees and administrators',
    'landing.advancedReporting': 'Advanced Reporting',
    'landing.advancedReportingDesc': 'Comprehensive analytics with export capabilities for CSV and PDF reports',
    'landing.antiFraudSystem': 'Anti-Fraud System',
    'landing.antiFraudSystemDesc': 'Mock location detection, device validation, and velocity checks to prevent attendance manipulation',
    'landing.howItWorks': 'How It Works',
    'landing.howItWorksSubtitle': 'Simple steps to modern attendance tracking',
    'landing.step1Title': 'Check In',
    'landing.step1Desc': 'Employees open the app and tap check-in. GPS automatically validates their location.',
    'landing.step2Title': 'Real-time Validation',
    'landing.step2Desc': 'System validates location, time, and shift schedule to determine attendance status.',
    'landing.step3Title': 'Analytics & Reports',
    'landing.step3Desc': 'Admins can view real-time data, generate reports, and manage make-up requests.',
    'landing.readyToModernize': 'Ready to Modernize Your Attendance System?',
    'landing.readyToModernizeDesc': 'Join organizations that trust our GPS-powered attendance system for accurate, real-time tracking.',
    'landing.startFreeToday': 'Start Free Today',
    'landing.footerText': '© 2025 All rights reserved. Gracefully made by Allah for Symbiotech.',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signOut': 'Sign Out',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.checkInToday': 'Check In Today',
    'dashboard.currentTime': 'Current time',
    'dashboard.alreadyCheckedIn': 'Already Checked In',
    'dashboard.time': 'Time',
    'dashboard.checkInNow': 'Check In Now',
    'dashboard.clockOut': 'Clock Out',
    'dashboard.clockOutNow': 'Clock Out Now',
    'dashboard.checkingLocation': 'Checking location...',
    'dashboard.makeValidLocation': 'Make sure you\'re at a valid location',
    'dashboard.validLocations': 'Valid Locations',
    'dashboard.radius': 'Radius',
    'dashboard.missedAttendance': 'Missed Attendance?',
    'dashboard.requestMakeup': 'Request make-up time for missed check-ins',
    'dashboard.thisMonth': 'This Month',
    'dashboard.totalDays': 'Total Days',
    'dashboard.present': 'Present',
    'dashboard.late': 'Late',
    'dashboard.absent': 'Absent',
    
    // Camera & Photo
    'camera.takingPhoto': 'Taking photo...',
    'camera.photoTaken': 'Photo captured successfully',
    'camera.photoFailed': 'Failed to capture photo',
    'camera.cameraNotAvailable': 'Camera not available',
    'camera.permissionDenied': 'Camera permission denied',
    'camera.usingFallback': 'Using fallback photo',
    'camera.photoSaved': 'Photo saved securely',
    'camera.attendanceWithPhoto': 'Attendance with photo successful',
    'camera.attendanceWithoutPhoto': 'Attendance without photo successful',
    'camera.securePhotoCapture': 'Secure photo capture',
    
    // Shift Selection
    'shift.todayShiftSelection': 'Today\'s Shift Selection',
    'shift.chooseWorkingShift': 'Choose your working shift for',
    'shift.selectShift': 'Select Shift',
    'shift.chooseShiftToday': 'Choose your shift for today',
    'shift.currentShift': 'Current Shift',
    'shift.startTime': 'Start Time',
    'shift.endTime': 'End Time',
    'shift.duration': 'Duration',
    'shift.dayType': 'Day Type',
    'shift.todayTimeline': 'Today\'s Timeline',
    'shift.start': 'Start',
    'shift.end': 'End',
    'shift.availableShifts': 'Available Shifts for',
    'shift.refreshShifts': 'Refresh Shifts',
    'shift.cannotChangeAfterAttendance': 'Shift cannot be changed after attendance has been recorded for today.',
    'shift.shiftChangedSuccess': 'Shift changed to',
    'shift.selectShiftFirst': 'Select Your Shift First',
    'shift.chooseShiftBeforeCheckin': 'Please choose your working shift above before checking in.',
    'shift.selectedShift': 'Selected Shift',
    'shift.shiftRequired': 'Shift Required',
    'shift.pleaseSelectShift': 'Please select your shift before checking in.',
    'shift.shiftStarts': 'Shift starts at',
    'shift.shiftActive': 'Shift is active until',
    'shift.shiftEnded': 'Shift ended at',
    
    // Shift Status
    'shift.status.active': 'Active Now',
    'shift.status.upcoming': 'Upcoming',
    'shift.status.ended': 'Ended',
    'shift.status.before': 'Before Shift',
    'shift.status.during': 'During Shift',
    'shift.status.after': 'After Shift',
    
    // Day Types
    'dayType.weekday': 'Weekday',
    'dayType.weekend': 'Weekend',
    'dayType.holiday': 'Holiday',
    'dayType.all': 'All Days',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcomeBack': 'Welcome back',
    'admin.reports': 'Reports',
    'admin.users': 'Users',
    'admin.devices': 'Devices',
    'admin.locations': 'Locations',
    'admin.shifts': 'Shifts',
    'admin.makeupRequests': 'Make-up Requests',
    
    // Analytics
    'analytics.todayOverview': 'Today\'s Overview',
    'analytics.presentToday': 'Present Today',
    'analytics.lateToday': 'Late Today',
    'analytics.absentToday': 'Absent Today',
    'analytics.totalEmployees': 'Total Employees',
    'analytics.activeUsers': 'Active users',
    'analytics.ofTotal': 'of total',
    'analytics.performanceMetrics': 'Performance Metrics',
    'analytics.attendanceRate': 'Attendance Rate',
    'analytics.punctualityRate': 'Punctuality Rate',
    'analytics.thisMonth': 'This Month',
    'analytics.fromLastMonth': 'from last month',
    'analytics.securityLocationAnalytics': 'Security & Location Analytics',
    'analytics.securityRiskDistribution': 'Security Risk Distribution',
    'analytics.lowRisk': 'Low Risk',
    'analytics.mediumRisk': 'Medium Risk',
    'analytics.highRisk': 'High Risk',
    'analytics.popularLocations': 'Popular Locations',
    'analytics.checkIns': 'check-ins',
    'analytics.analyticsDashboard': 'Analytics Dashboard',
    'analytics.detailedReports': 'Detailed Reports',
    'analytics.noLocationData': 'No location data available',
    
    // Device Management
    'device.deviceManagement': 'Device Management',
    'device.manageDevices': 'Manage user devices, reset fingerprints, and monitor security',
    'device.filterByUser': 'Filter by User',
    'device.allUsers': 'All Users',
    'device.refresh': 'Refresh',
    'device.registeredDevices': 'Registered Devices',
    'device.uniqueDevicesFound': 'unique devices found',
    'device.user': 'User',
    'device.deviceInfo': 'Device Info',
    'device.riskLevel': 'Risk Level',
    'device.lastSeen': 'Last Seen',
    'device.securityStatus': 'Security Status',
    'device.warnings': 'warnings',
    'device.clean': 'Clean',
    'device.deviceDetails': 'Device Details',
    'device.detailedInformation': 'Detailed information about this device and its security status',
    'device.deviceFingerprint': 'Device Fingerprint',
    'device.deviceInformation': 'Device Information',
    'device.securityWarnings': 'Security Warnings',
    'device.lastActivity': 'Last Activity',
    'device.resetDevice': 'Reset Device',
    'device.resetDeviceFingerprint': 'Reset Device Fingerprint',
    'device.resetConfirmation': 'This action will reset the device fingerprint for this user. They will need to re-register their device on next login.',
    'device.confirmReset': 'Confirm Reset',
    'device.currentRisk': 'Current Risk',
    'device.processing': 'Processing...',
    'device.deviceResetSuccess': 'Device fingerprint reset successfully for user',
    'device.unknownDevice': 'Unknown Device',
    
    // Security
    'security.securityStatus': 'Security Status',
    'security.mockLocationDetection': 'Mock Location Detection',
    'security.deviceFingerprinting': 'Device Fingerprinting',
    'security.velocityCheck': 'Velocity Check',
    'security.active': 'Active',
    'security.securityAlert': 'Security Alert - Risk Level',
    'security.securityWarning': 'Security Warning',
    'security.locationValidationFailed': 'Location validation failed. Risk level',
    'security.confidence': 'Confidence',
    'security.proceedQuestion': 'Do you want to proceed?',
    'security.protectedByAntiFraud': 'Protected by anti-fraud system',
    
    // Device Management
    'admin.deviceManagement': 'Device Management',
    'admin.manageDevices': 'Manage user devices and security',
    'admin.deviceInfo': 'Device Info',
    'admin.lastSeen': 'Last Seen',
    'admin.securityStatus': 'Security Status',
    'admin.resetDevice': 'Reset Device',
    'admin.deviceReset': 'Device reset successfully!',
    'admin.resetConfirm': 'Are you sure you want to reset this device?',
    'admin.deviceDetails': 'Device Details',
    'admin.securityWarnings': 'Security Warnings',
    'admin.deviceFingerprint': 'Device Fingerprint',
    'admin.riskLevel': 'Risk Level',
    'admin.clean': 'Clean',
    'admin.warnings': 'warnings',
    
    // Admin Reports
    'admin.filterExport': 'Filter & Export',
    'admin.filterAttendanceData': 'Filter attendance data and export reports',
    'admin.startDate': 'Start Date',
    'admin.endDate': 'End Date',
    'admin.employee': 'Employee',
    'admin.allEmployees': 'All employees',
    'admin.allStatuses': 'All statuses',
    'admin.allMethods': 'All methods',
    'admin.regular': 'Regular',
    'admin.makeup': 'Make-up',
    'admin.reset': 'Reset',
    'admin.csv': 'CSV',
    'admin.attendanceReport': 'Attendance Report',
    'admin.recordsFound': 'records found',
    'admin.date': 'Date',
    'admin.exportSuccess': 'Report exported successfully!',
    
    // Hours Report - NEW TRANSLATIONS
    'admin.hoursReport': 'Hours Report',
    'admin.hoursReportDescription': 'Analyze employee working hours based on shifts and actual time',
    'admin.expectedHours': 'Expected Hours',
    'admin.actualHours': 'Actual Hours',
    'admin.missingHours': 'Missing Hours',
    'admin.overtimeHours': 'Overtime Hours',
    'admin.workingDays': 'Working Days',
    'admin.totalExpectedHours': 'Total Expected Hours',
    'admin.totalActualHours': 'Total Actual Hours',
    'admin.totalMissingHours': 'Total Missing Hours',
    'admin.totalOvertimeHours': 'Total Overtime Hours',
    'admin.averageHoursPerDay': 'Average Hours per Day',
    'admin.hoursEfficiency': 'Hours Efficiency',
    'admin.noClockOut': 'No Clock Out',
    'admin.incomplete': 'Incomplete',
    'admin.hoursAnalysis': 'Hours Analysis',
    'admin.employeeHoursSummary': 'Employee Hours Summary',
    
    // Admin User Management
    'admin.userManagement': 'User Management',
    'admin.manageUsers': 'Manage user accounts and roles',
    'admin.admin': 'Admin',
    'admin.user': 'User',
    
    // Admin Location Management
    'admin.locationManagement': 'Location Management',
    'admin.manageValidLocations': 'Manage valid attendance locations with GPS coordinates',
    'admin.addLocation': 'Add Location',
    'admin.editLocation': 'Edit Location',
    'admin.addNewLocation': 'Add New Location',
    'admin.setupValidLocation': 'Set up a valid attendance location with GPS coordinates and radius.',
    'admin.locationName': 'Location Name',
    'admin.locationNamePlaceholder': 'e.g., Main Office',
    'admin.latitude': 'Latitude',
    'admin.longitude': 'Longitude',
    'admin.radiusMeters': 'Radius (meters)',
    'admin.active': 'Active',
    'admin.coordinates': 'Coordinates',
    'admin.status': 'Status',
    'admin.inactive': 'Inactive',
    'admin.deleteLocationConfirm': 'Are you sure you want to delete this location?',
    'admin.locationCreated': 'Location created successfully!',
    'admin.locationUpdated': 'Location updated successfully!',
    'admin.locationDeleted': 'Location deleted successfully!',
    
    // Admin Shift Management
    'admin.shiftManagement': 'Shift Management',
    'admin.manageWorkShifts': 'Manage work shifts and their time schedules',
    'admin.addShift': 'Add Shift',
    'admin.editShift': 'Edit Shift',
    'admin.addNewShift': 'Add New Shift',
    'admin.setupWorkShift': 'Set up work shift times for attendance tracking.',
    'admin.shiftName': 'Shift Name',
    'admin.shiftNamePlaceholder': 'e.g., Morning Shift',
    'admin.startTime': 'Start Time',
    'admin.endTime': 'End Time',
    'admin.duration': 'Duration',
    'admin.hours': 'hours',
    'admin.dayType': 'Day Type',
    'admin.selectDayType': 'Select Day Type',
    'admin.dayType.weekday': 'Weekday',
    'admin.dayType.weekend': 'Weekend',
    'admin.dayType.holiday': 'Holiday',
    'admin.dayType.all': 'All Days',
    'admin.deleteShiftConfirm': 'Are you sure you want to delete this shift?',
    'admin.shiftCreated': 'Shift created successfully!',
    'admin.shiftUpdated': 'Shift updated successfully!',
    'admin.shiftDeleted': 'Shift deleted successfully!',
    
    // Admin Makeup Requests
    'admin.makeupRequestsTitle': 'Make-up Requests',
    'admin.reviewProcessRequests': 'Review and process employee make-up attendance requests',
    'admin.reason': 'Reason',
    'admin.submitted': 'Submitted',
    'admin.reviewMakeupRequest': 'Review Make-up Request',
    'admin.reviewDetails': 'Review the details and approve or reject this make-up request.',
    'admin.dateOfMissed': 'Date of Missed Attendance',
    'admin.supportingDocument': 'Supporting Document',
    'admin.viewDocument': 'View Document',
    'admin.adminNotes': 'Admin Notes',
    'admin.addNotesDecision': 'Add notes about your decision...',
    'admin.reject': 'Reject',
    'admin.approve': 'Approve',
    'admin.makeupRequestApproved': 'Make-up request approved and attendance record created!',
    'admin.makeupRequestRejected': 'Make-up request rejected.',
    
    // Makeup Request Dialog
    'makeup.requestMakeup': 'Request Make-up',
    'makeup.requestMakeupTime': 'Request Make-up Time',
    'makeup.requestMakeupDescription': 'Submit a request for missed attendance. Admin will review and approve.',
    'makeup.dateOfMissedAttendance': 'Date of Missed Attendance',
    'makeup.reasonPlaceholder': 'Explain why you missed the attendance...',
    'makeup.supportingDocumentOptional': 'Supporting Document URL (Optional)',
    'makeup.documentUrlPlaceholder': 'https://example.com/document.pdf',
    'makeup.submitting': 'Submitting...',
    'makeup.submitRequest': 'Submit Request',
    'makeup.requestSubmittedSuccess': 'Make-up request submitted successfully!',
    
    // Status
    'status.HADIR': 'PRESENT',
    'status.TERLAMBAT': 'LATE',
    'status.MAKE_UP': 'MAKE UP',
    'status.pending': 'PENDING',
    'status.approved': 'APPROVED',
    'status.rejected': 'REJECTED',
    
    // General
    'general.success': 'Success',
    'general.error': 'Error',
    'general.loading': 'Loading...',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    'general.delete': 'Delete',
    'general.edit': 'Edit',
    'general.add': 'Add',
    'general.view': 'View',
    'general.actions': 'Actions',
    'general.name': 'Name',
    'general.created': 'Created',
    'general.role': 'Role',
    'general.create': 'Create',
    'general.update': 'Update',
    'general.time': 'Time',
    'general.location': 'Location',
    'general.method': 'Method',
    'general.close': 'Close',
    
    // Attendance
    'attendance.history': 'Attendance History',
    'attendance.status': 'Status',
    'attendance.method': 'Method',
    'attendance.location': 'Location',
    'attendance.reason': 'Reason',
    'attendance.noRecords': 'No attendance records found',
    
    // Notifications
    'notification.locationError': 'Location Error',
    'notification.notValidLocation': 'You are not at a valid location for attendance',
    'notification.attendanceSuccess': 'Attendance successful! Status',
    'notification.roleUpdated': 'User role updated successfully!',
    
    // Language
    'language.indonesian': 'Bahasa Indonesia',
    'language.english': 'English'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'id';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};